apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster                   
metadata:
  name: toddb-prom-02                        
  namespace: monitoring                       
spec:
  distribution:
    version: v1.18                             
  topology:
    controlPlane:
      count: 1                                 
      class: best-effort-small                 
      storageClass: vsphere-with-kubernetes       
    workers:
      count: 4                                 
      class: best-effort-small                 
      storageClass: vsphere-with-kubernetes