apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster                   
metadata:
  # Name of cluster example tkg-cluster-01
  name: short-12                       
  # vSphere Workload Management Nameapace to deploy cluster to
  namespace: capacity-test                       
spec:
  distribution:
    version: v1.18                             
  topology:
    controlPlane:
      # Number of Nodes in Controlplane
      count: 1                                 
      #
      class: best-effort-small               
      #vSphere storage class to use get this from vsphere admin  
      storageClass: vsphere-with-kubernetes 
    workers:
      #
      count: 1                
      #                 
      class: best-effort-xlarge     
      #vSphere storage class to use get this from vsphere admin
      storageClass: vsphere-with-kubernetes 
  settings:
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["10.96.0.0/16"] 
      pods:
        cidrBlocks: ["172.20.0.0/16"]
      serviceDomain: "ben.local"